# contact_links:
#   - name: 💬 Discussions
#     url: https://github.com/unjs/packageName/discussions
#     about: Use discussions if you have an idea for improvement and asking questions
#   - name: 🔗 Nuxt related Issues
#     url: https://github.com/nuxt/framework/issues/new/choose
#     about: Please open an issue in nuxt/framework to discuss
